### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vincetek** [Pavion/tvstreamrecord#43]
hello, I'm contacting you because I have this error that appears in the log, can you help me?
Thank you Best regards

(2020-02-22 21:49:56.969 | Output file /volume1/video/enregistrements_TV/20200222214956 - TF1_FULL_HD.ts could not be created. Please check your settings. Description: [Errno socket error] [Errno -2] Name or service not known)
-- | --

**Comment by Pavion** [comment]
Hi! 

It looks like your input stream is not accessible. 
Please check, whether your stream is playable with a standard video player such as VLC.

If it's correct, you may want to try ffmpeg instead of default http grabber. For using ffmpeg please add your stream protocoll `http` into `config` -> `ffmpeg support` -> `Stream types ...` so it looks like: 

```
rtmp rtp rtsp http
```

You'd need ffmpeg for this, which is distributed with Synology video station (must be installed). 

You *may* need to use the complete path for ffmpeg: 
```
/volume1/@appstore/VideoStation/bin/ffmpeg  
```

If it still not works, please provide additional information: 
- which system
- which stream you're trying to record
- larger log excerpt

BR Pav

**Comment by vincetek** [comment]
I will try this, thank you, cordially

Vincent

     Le dimanche 23 février 2020 à 09:35:55 UTC+1, Pavion <notifications@github.com> a écrit :  
 
 
Hi!

It looks like your input stream is not accessible.
Please check, whether your stream is playable with a standard video player such as VLC.

If it's correct, you may want to try ffmpeg instead of default http grabber. For using ffmpeg please add your stream protocoll http into config -> ffmpeg support -> Stream types ... so it looks like:
rtmp rtp rtsp http
You'd need ffmpeg for this, which is distributed with Synology video station (must be installed).

You may need to use the complete path for ffmpeg:
/volume1/@appstore/VideoStation/bin/ffmpeg  
If it still not works, please provide additional information:
   
   - which system
   - which stream you're trying to record
   - larger log excerpt

BR Pav
